### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Liibo111** [reinew/borsdata-api-php#2]
Hi.

Wondering about how I can do if I want to take our for example all swedish companies and take the latest 5 quarter. That works for me, but they are not named then. Only when I take function 1 they are named.

They then having name like "instrument": 2,

But how can I make so it showing names instead of instrument numbers?

Big thanks for your help

**Comment by reinew** [comment]
You have to do two queries, one for the instrument names and id and save that in for example a variable or a database, and then query for the data you want, then combine the data on instrument id.
